In [33]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt

def importarPQR():
    datos = pd.read_excel('FP.xlsx', header=2, nrows=5)
    return datos

def importarTiempos():
    datos = pd.read_excel('FP.xlsx', header=15, nrows=10)
    return datos

def importarTiemposAlisto(numeroMaquina):
    datos = pd.read_excel('FP.xlsx',sheet_name=1, header=14*(numeroMaquina-1)+4, nrows=10)
    return datos

datosExcel = importarPQR()
datosTiempos = importarTiempos()

ultimoTiempo = 0
tiempoGlobal = 0
contadorTiempo = [0, 0, 0, 0, 0]

colaMaquina1 = []
colaMaquina2 = []
colaMaquina3 = []
colaMaquina4 = []
colaMaquina5 = []

maquinas = [colaMaquina1, colaMaquina2, colaMaquina3, colaMaquina4, colaMaquina5]


def iniciarCromosoma():
    return np.array([10, 3, 7, 4, 5])

secuenciaPrincipal = iniciarCromosoma()


def asignarRestantes():
    global datosExcel
    global maquinas
    global contadorTiempo
    faltar = [1, 2, 6, 8, 9]
    for trabajo in faltar:
        variableExcel = 'J' + str(trabajo)
        maquina = datosExcel[variableExcel][0]
        maquinas[maquina-1] += [trabajo]
    tiempos = tiemposEnCola(secuenciaPrincipal, extraerElementosMaquinas())
    contador = 0
    for t in tiempos:
        contadorTiempo[contador] += t
        contador += 1


def secuencia():
    global datosTiempos
    global maquinas
    global ultimoTiempo
    global tiempoGlobal
    global contadorTiempo
    for i in range(len(maquinas)):
        tiempos = auxiliarOrdenarTiempos(maquinas[i], secuenciaPrincipal[i], i+1)
        nuevaCola = ordenarPorTiempos(tiempos, maquinas[i])
        maquinas[i] = nuevaCola
    print('Secuencia')
    print(secuenciaPrincipal)
    print('Tiempos')
    print(contadorTiempo)
    print('Tiempo')
    print(tiempoGlobal)
    print('Colas')
    print(maquinas)
    a = np.copy(np.array(contadorTiempo))
    x = np.where(a > tiempoGlobal)
    y = np.where(a <= tiempoGlobal)
    x = a[x]
    sm = np.argmin(x)
    a[y] = x[sm] + 1
    indice = np.argmin(a)
    cola = auxiliarEncontrarCola(indice, secuenciaPrincipal[indice])
    maquinas[cola-1] += [secuenciaPrincipal[indice]]
    prenderMaquina(cola)
    tiempoGlobal += contadorTiempo[indice] - ultimoTiempo
    ultimoTiempo = contadorTiempo[indice]
    secuenciaPrincipal[indice] = maquinas[indice][0]
    maquinas[indice] = maquinas[indice][1:]
    tiemp = tiemposEnCola(secuenciaPrincipal, extraerElementosMaquinas())[indice]
    contadorTiempo[indice] += tiemp
    contador = 0
    for tiemposAux in contadorTiempo:
        if tiemposAux < tiempoGlobal:
            contadorTiempo[contador] = tiempoGlobal
        contador += 1


def prenderMaquina(cola):
    global contadorTiempo
    if len(maquinas[cola - 1]) == 1:
        a = auxiliarOrdenarTiempos(maquinas[cola-1], maquinas[cola-1][0], cola)[0]
        contadorTiempo[cola-1] += a


def extraerElementosMaquinas():
    listaResultado = []
    global maquinas
    for maq in maquinas:
        if maq != []:
            listaResultado += [maq[0]]
        else:
            listaResultado += [None]
    return listaResultado


def auxiliarEncontrarCola(posicionTrabajo, trabajo):
    global datosExcel
    j = 'J' + str(trabajo)
    proceso = datosExcel[j]
    contador = 0
    for cola in proceso:
        if posicionTrabajo+1 == cola:
            if contador != 5:
                return proceso[contador + 1]
            else:
                return None
        contador += 1
    return None

def auxiliarOrdenarTiempos(colasMaquina, proceso, numeroMaquina):
    global datosTiempos
    listaTiempos = []
    for procesoAux in colasMaquina:
        datosAlisto = importarTiemposAlisto(numeroMaquina)
        Ji = 'J' + str(proceso)
        Jj = procesoAux-1
        t1 = datosTiempos['M' + str(numeroMaquina)][procesoAux-1]
        t2 = datosAlisto[Ji][Jj]
        listaTiempos += [t1 + t2]
    return listaTiempos

def ordenarPorTiempos(listaTiempos, listaOrdenar):
    nuevaLista = []
    indices = np.argsort(listaTiempos)
    for i in indices:
        nuevaLista += [listaOrdenar[i]]
    return nuevaLista

def tiemposEnCola(secuencia, colas):
    tiemposAux = []
    contador = 0
    for elemento in colas:
        if elemento is not None:
            tiemposAux += auxiliarOrdenarTiempos([elemento], secuencia[contador], contador+1)
            contador += 1
        else:
            tiemposAux += [0]

    return tiemposAux

asignarRestantes()
for i in range(25):
    secuencia()





Secuencia
[10  3  7  4  5]
Tiempos
[63, 26, 48, 40, 0]
Tiempo
0
Colas
[[1], [8, 9], [2], [6], []]
Secuencia
[10  8  7  4  5]
Tiempos
[63, 70, 48, 40, 26]
Tiempo
26
Colas
[[1], [9], [2], [6, 3], []]
Secuencia
[10  8  7  6  5]
Tiempos
[63, 70, 48, 107, 40]
Tiempo
40
Colas
[[1], [9], [2, 4], [3], []]
Secuencia
[10  8  2  6  5]
Tiempos
[63, 70, 93, 107, 90]
Tiempo
48
Colas
[[1], [9], [4], [3], [7]]
Secuencia
[1 8 2 6 5]
Tiempos
[63, 70, 93, 107, 90]
Tiempo
63
Colas
[[], [9], [4], [3], [10, 7]]
Secuencia
[1 9 2 6 5]
Tiempos
[70, 70, 93, 107, 90]
Tiempo
70
Colas
[[], [], [4], [8, 3], [10, 7]]
Secuencia
[ 1  9  2  6 10]
Tiempos
[90, 108, 93, 107, 147]
Tiempo
90
Colas
[[], [5], [4], [8, 3], [7]]
Secuencia
[ 1  9  4  6 10]
Tiempos
[93, 108, 93, 107, 147]
Tiempo
93
Colas
[[], [5], [], [8, 3], [2, 7]]
Secuencia
[ 1  9  4  8 10]
Tiempos
[107, 108, 148, 148, 147]
Tiempo
107
Colas
[[], [5], [6], [3], [2, 7]]
Secuencia
[ 1  5  4  8 10]
Tiempos
[142, 108, 148, 148, 147]
Tiempo
108
Colas
[[9], [], [6],

ValueError: attempt to get argmin of an empty sequence

In [5]:
x = [0,1,2,3]
x[4] = 1
x

IndexError: list assignment index out of range